version: '3.8'

services:
  meridian:
    build:
      context: ../
      dockerfile: ./meridian/Dockerfile
    container_name: meridian
    restart: no
    ports:
      - ${MERIDIAN_LISTEN_PORT}:${MERIDIAN_LISTEN_PORT}
    environment:
      - PULSAR_ADDRESS=${PULSAR_ADDRESS}
      - NEO4J_ADDRESS=${MERIDIAN_NEO4J_ADDRESS}
      - NEO4J_DB_NAME=${MERIDIAN_NEO4J_DB_NAME}
      - LISTEN_ADDRESS=0.0.0.0:${MERIDIAN_LISTEN_PORT}
    depends_on:
      meridian_neo4j:
        condition: service_healthy

  meridian_neo4j:
    image: neo4j:4.4.12
    container_name: meridian_neo4j
    restart: on-failure
    ports:
      - ${MERIDIAN_NEO4J_HTTP_PORT}:${MERIDIAN_NEO4J_HTTP_PORT}
      - ${MERIDIAN_NEO4J_BOLT_PORT}:${MERIDIAN_NEO4J_BOLT_PORT}
    environment:
      - NEO4J_dbms_connector_bolt_listen__address=:${MERIDIAN_NEO4J_BOLT_PORT}
      - NEO4J_dbms_connector_http_listen__address=:${MERIDIAN_NEO4J_HTTP_PORT}
      - NEO4J_dbms_security_auth__enabled=${MERIDIAN_NEO4J_AUTH_ENABLED}
    volumes:
      - meridian_neo4j_data:/data
      # - meridian_neo4j_logs:/logs
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  pulsar:
    build:
      context: ../
      dockerfile: ./pulsar/Dockerfile
    container_name: pulsar
    restart: on-failure
    environment:
      - ETCD_ADDRESS=${PULSAR_ETCD_ADDRESS}
      - LISTEN_ADDRESS=${PULSAR_LISTEN_ADDRESS}
    depends_on:
      - pulsar_etcd

  pulsar_etcd:
    image: 'bitnami/etcd:latest'
    container_name: pulsar_etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://${PULSAR_ETCD_ADDRESS}
    volumes:
      - pulsar_etcd_data:/bitnami/etcd

volumes:
  meridian_neo4j_data:
    driver: local
  meridian_neo4j_logs:
    driver: local
  pulsar_etcd_data:
    driver: local