// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: meridian-model.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyscallRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names  []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Action string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *SyscallRule) Reset() {
	*x = SyscallRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meridian_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyscallRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallRule) ProtoMessage() {}

func (x *SyscallRule) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallRule.ProtoReflect.Descriptor instead.
func (*SyscallRule) Descriptor() ([]byte, []int) {
	return file_meridian_model_proto_rawDescGZIP(), []int{0}
}

func (x *SyscallRule) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *SyscallRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type SeccompProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version       string         `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	DefaultAction string         `protobuf:"bytes,3,opt,name=defaultAction,proto3" json:"defaultAction,omitempty"`
	Syscalls      []*SyscallRule `protobuf:"bytes,4,rep,name=syscalls,proto3" json:"syscalls,omitempty"`
}

func (x *SeccompProfile) Reset() {
	*x = SeccompProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meridian_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeccompProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeccompProfile) ProtoMessage() {}

func (x *SeccompProfile) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeccompProfile.ProtoReflect.Descriptor instead.
func (*SeccompProfile) Descriptor() ([]byte, []int) {
	return file_meridian_model_proto_rawDescGZIP(), []int{1}
}

func (x *SeccompProfile) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SeccompProfile) GetDefaultAction() string {
	if x != nil {
		return x.DefaultAction
	}
	return ""
}

func (x *SeccompProfile) GetSyscalls() []*SyscallRule {
	if x != nil {
		return x.Syscalls
	}
	return nil
}

type ApplyAppConfigCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId          string             `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	NamespaceName  string             `protobuf:"bytes,2,opt,name=namespaceName,proto3" json:"namespaceName,omitempty"`
	AppName        string             `protobuf:"bytes,3,opt,name=appName,proto3" json:"appName,omitempty"`
	SeccompProfile string             `protobuf:"bytes,4,opt,name=seccompProfile,proto3" json:"seccompProfile,omitempty"`
	Quotas         map[string]float64 `protobuf:"bytes,5,rep,name=quotas,proto3" json:"quotas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Strategy       string             `protobuf:"bytes,6,opt,name=strategy,proto3" json:"strategy,omitempty"`
}

func (x *ApplyAppConfigCommand) Reset() {
	*x = ApplyAppConfigCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meridian_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyAppConfigCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyAppConfigCommand) ProtoMessage() {}

func (x *ApplyAppConfigCommand) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyAppConfigCommand.ProtoReflect.Descriptor instead.
func (*ApplyAppConfigCommand) Descriptor() ([]byte, []int) {
	return file_meridian_model_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyAppConfigCommand) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ApplyAppConfigCommand) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *ApplyAppConfigCommand) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ApplyAppConfigCommand) GetSeccompProfile() string {
	if x != nil {
		return x.SeccompProfile
	}
	return ""
}

func (x *ApplyAppConfigCommand) GetQuotas() map[string]float64 {
	if x != nil {
		return x.Quotas
	}
	return nil
}

func (x *ApplyAppConfigCommand) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

var File_meridian_model_proto protoreflect.FileDescriptor

var file_meridian_model_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x65, 0x72, 0x69, 0x64, 0x69, 0x61, 0x6e, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a,
	0x0b, 0x53, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x80, 0x01, 0x0a, 0x0e, 0x53,
	0x65, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a,
	0x08, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x52,
	0x75, 0x6c, 0x65, 0x52, 0x08, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x22, 0xae, 0x02,
	0x0a, 0x15, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x73, 0x65, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x70,
	0x70, 0x6c, 0x79, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x1a, 0x39, 0x0a, 0x0b, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x22,
	0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x31, 0x32,
	0x73, 0x2f, 0x6d, 0x65, 0x72, 0x69, 0x64, 0x69, 0x61, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meridian_model_proto_rawDescOnce sync.Once
	file_meridian_model_proto_rawDescData = file_meridian_model_proto_rawDesc
)

func file_meridian_model_proto_rawDescGZIP() []byte {
	file_meridian_model_proto_rawDescOnce.Do(func() {
		file_meridian_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_meridian_model_proto_rawDescData)
	})
	return file_meridian_model_proto_rawDescData
}

var file_meridian_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_meridian_model_proto_goTypes = []interface{}{
	(*SyscallRule)(nil),           // 0: proto.SyscallRule
	(*SeccompProfile)(nil),        // 1: proto.SeccompProfile
	(*ApplyAppConfigCommand)(nil), // 2: proto.ApplyAppConfigCommand
	nil,                           // 3: proto.ApplyAppConfigCommand.QuotasEntry
}
var file_meridian_model_proto_depIdxs = []int32{
	0, // 0: proto.SeccompProfile.syscalls:type_name -> proto.SyscallRule
	3, // 1: proto.ApplyAppConfigCommand.quotas:type_name -> proto.ApplyAppConfigCommand.QuotasEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meridian_model_proto_init() }
func file_meridian_model_proto_init() {
	if File_meridian_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meridian_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyscallRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meridian_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeccompProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meridian_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyAppConfigCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meridian_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meridian_model_proto_goTypes,
		DependencyIndexes: file_meridian_model_proto_depIdxs,
		MessageInfos:      file_meridian_model_proto_msgTypes,
	}.Build()
	File_meridian_model_proto = out.File
	file_meridian_model_proto_rawDesc = nil
	file_meridian_model_proto_goTypes = nil
	file_meridian_model_proto_depIdxs = nil
}
